### PR TITLE
compiler: Fix errors in globs

### LINKED ISSUE #1676: glob compiler crash
Adding `label.near` to the `**` glob crashes.

```d2
**: {
  style.border-radius: 16
}

**: {
  &label: end
  label: ⬤
  shape: circle
  height: 10
  width: 10
}

**: {
  &label: start
  label: ⬤
  label.near: center
  style.fill: black
  shape: circle
  height: 10
  width: 10
}

**: {
  &shape: diamond
  label: ""
  height: 30
  width: 30
}

start -> Check PIN

Check PIN: {
  direction: right

  start -> Enter PIN
  choice.shape: diamond

  Enter PIN -> choice: "/check PIN"
  choice -> Enter PIN: "[pin invalid]"
  choice -> end: "[pin OK]"
}

Check PIN -> Search Network: "[pin OK]"
Search Network -> Ready: network found

Check PIN -> Off: power off
Search Network -> Off: power off
Ready -> Off: power off
```

### PR DESCRIPTION
**Pull request by alixander**
fixes #1676

1. This picks up refs set by globs so that the error gets the right ref.
2. Which also adds a dedupe to the compiler list of errors since keys set by globs, if errored, will report multiple errors emanating from the same range.

### CODE REVIEW

File: d2ir/d2ir.go [hunk 1]
```diff
@@ -318,11 +318,19 @@ func (f *Field) Copy(newParent Node) Node {
 }
 
 func (f *Field) LastPrimaryRef() Reference {
+	var lastGlobSet Reference
```
Comment (gavin-ts) [inline d2ir/d2ir.go:321]: I think `(e *Edge) LastPrimaryRef()` might also need this if there are multiple globs affecting an edge?

Comment (gavin-ts) [reply d2ir/d2ir.go:321]: hmm adding 

```d2
(** -> **)[*]: {
	label.near: center
}
```

to the test correctly shows the new error, maybe this isn't needed?

**Review by gavin-ts — APPROVED** [review]

File: d2ir/d2ir.go (hunk 1 above)
Comment (gavin-ts) [reply d2ir/d2ir.go:321]: oh wait

```d2
**: {
  label: hi
  label.near: center
}
(** -> **)[*]: {
	label.near: top-center
}
(** -> **)[*]: {
	label.near: invalid
}

x: {
  a -> b
}
```

has the line number of the first valid near instead of the 2nd
```
        d2/testdata/d2compiler/TestCompile2/globs/double-glob-err-val.d2:4:3: invalid "near" field
        d2/testdata/d2compiler/TestCompile2/globs/double-glob-err-val.d2:7:2: invalid "near" field
```

line 7 should be 10 right?

**Review by gavin-ts — CHANGES_REQUESTED** [review]

File: d2ir/d2ir.go (hunk 1 above)
Comment (alixander) [reply d2ir/d2ir.go:321]: gooood catch

**Review by gavin-ts — APPROVED** [review]

File: d2ir/d2ir.go [hunk 2]
```diff
@@ -318,11 +318,21 @@ func (f *Field) Copy(newParent Node) Node {
...
 	for i := len(f.References) - 1; i >= 0; i-- {
-		if f.References[i].Primary() && !f.References[i].DueToLazyGlob() {
-			return f.References[i]
+		if f.References[i].Primary() {
+			if f.References[i].DueToLazyGlob() {
+				if lastGlobSet == nil {
+					lastGlobSet = f.References[i]
+				}
```
Comment (gavin-ts) [inline d2ir/d2ir.go:327]: can this become `return f.References[i]`? when does it need to keep iterating?

Comment (alixander) [reply d2ir/d2ir.go:327]: i thought it was that case, but i realized the last ref always wins, so you're right, it can become that
